// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAL_qzjg481R9ojh5_O_InIkrHF1YrG6x8',
//     appId: '1:829518825553:android:18be954ade91bf94255070',
//     messagingSenderId: '829518825553',
//     projectId: 'cl-3718---villagkart',
//     storageBucket: 'cl-3718---villagkart.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD2itcuxZqXmWdQMkReyGw6pfu7LYglIqg',
//     appId: '1:829518825553:ios:48d516355e73440f255070',
//     messagingSenderId: '829518825553',
//     projectId: 'cl-3718---villagkart',
//     storageBucket: 'cl-3718---villagkart.firebasestorage.app',
//     androidClientId:
//         '829518825553-56t3mbffvnt81na47r15vfov8f0et240.apps.googleusercontent.com',
//     iosClientId:
//         '829518825553-vg3pit5gslfeptq5ffhqnke43l4d8nk2.apps.googleusercontent.com',
//     iosBundleId: 'com.villagkartview.customer',
//   );
// }
